#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
projDir <- "~/Documents/Projects/DataScience/CapstoneProject_JHSK/"
srcDir <- paste0(projDir, "capstonegitrepo/")
source(paste0(srcDir, "CreateModel.R"))

library(shiny)

ui <- fluidPage(
    # Stylesheet from [Bootswatch](https://bootswatch.com/)
    theme = "bootstrap.solar.css",
                
   # Application title
   titlePanel("Next-Word Predictor"),
   
   # User input and word predictions
   sidebarLayout(
      sidebarPanel(
         # User input and explanation
         textInput("inputText",
                   "Begin typing.  When you enter a SPACE, the next word is predicted:",
                   placeholder = "Type here"),

         ## Predictions (each word in a button)
         tags$h4("Top 5 Next-Word Predictions"),
         uiOutput("preds", inline = TRUE),
         
         # Algorithm notes and attribution
         tags$h4(" "),
         tags$p("These next-word predictions are generated by an implementation of the ",
                tags$em("Stupid Backoff "),
                "algorithm described in the paper, ",
                tags$a(href="http://www.aclweb.org/anthology/D07-1090.pdf", 
                       "Large Language Models in Machine Translation (Brants, Popat, Xu, Och & Dean)"))
      ),

      # Prediction log
      mainPanel(
          tags$h3("Prediction Scoring Log"),
          tableOutput("predlog")
      )
   )
)

# Load the ngram tables once per R session
ngTables <- loadNgTables("train")

server <- function(input, output) {
    
    predsList <- reactiveValues()
    predsList[["predLog"]] <- data.table(
        "Input" = character(0),
        "Next Word" = character(0),
        "Score" = numeric(0)
    )
    
    output$preds <- renderUI({
        # Detect trailing space
        foundTrailing <- grepl("[ \t]+$", input$inputText)
        
        # If there's a trailing space, get the last maxN-1 tokens and predict.
        predList <- list()
        if (foundTrailing) {
            inWords <- getNGrams(input$inputText, 1)
            inputLen <- 0
            predInput <- ""
            if ( length(inWords) >= maxN-1 ) {
                inputLen <- maxN-1
                predInput <- inWords[(length(inWords)-inputLen+1):length(inWords)]
            }
            else {
                if ( length(inWords) > 0 ) {
                    inputLen <- length(inWords)
                    predInput <- inWords
                }
            }
            # print(paste0("Prediction input: (", paste0(predInput, collapse=" "), ")"))
            # print(paste0("Input length: (", inputLen, ")"))
            
            sbScores <- predictionFlow(inputLen+1, paste0(predInput, collapse=" "), ngTables, 5)
            for ( predIdx in 1:nrow(sbScores) ) {
                # Predictions (each word in a button)
                predList[[predIdx]] <- tags$button(type="button", name="predbtn", 
                                                   value=paste0("predbtn", predIdx), 
                                                   disabled=NA, 
                                                   sbScores$nextword[predIdx])
            }
            isolate({
                names(sbScores) <- c("Input", "Next Word", "Score")
                scoresList <- list(sbScores, predsList[["predLog"]])
                predsList[["predLog"]] <- rbindlist(scoresList, use.names = FALSE)
            })
        }
        
        tagList(predList)
    })
    
    output$predlog <- renderTable({
        predsList[["predLog"]]
    }, bordered = TRUE)
}

















# Run the application 
shinyApp(ui = ui, server = server)


